# Generated by Django 3.2.10 on 2023-04-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('airplane_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Econo', models.IntegerField()),
                ('first', models.IntegerField()),
                ('busi', models.IntegerField()),
                ('count', models.IntegerField()),
                ('basic_cost', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('Eco_fare', models.IntegerField()),
                ('first_fare', models.IntegerField()),
                ('busi_fare', models.IntegerField()),
                ('date', models.DateField()),
                ('distance', models.IntegerField()),
                ('last_date', models.DateField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airplanetype')),
                ('dest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='api.airport')),
                ('origin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='api.airport')),
            ],
        ),
        migrations.CreateModel(
            name='flight_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('origin', models.CharField(max_length=200)),
                ('dest', models.CharField(max_length=200)),
                ('prf_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Econo', models.IntegerField()),
                ('T_Bussi', models.IntegerField()),
                ('T_First', models.IntegerField()),
                ('date', models.DateField()),
                ('Income', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
        ),
        migrations.CreateModel(
            name='flight_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_no', models.CharField(max_length=500)),
                ('Class', models.CharField(max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users_permissions', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_trav', models.IntegerField()),
                ('date', models.DateField()),
                ('traveller', models.CharField(max_length=150)),
                ('tra_age', models.CharField(max_length=150)),
                ('fare', models.IntegerField()),
                ('seats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.flight_seat')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.customuser')),
            ],
        ),
    ]
