# Generated by Django 3.2.10 on 2023-04-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='day',
            field=models.CharField(default='Wednesday', max_length=15),
        ),
    ]
